
spring:
  kafka:
    bootstrap-servers: my-cluster-kafka-bootstrap:9092
    streams:
      bootstrap-servers: my-cluster-kafka-bootstrap:9092
    properties:
      schema.registry.url: http://schema-registry:8081
      bootstrap.servers: ${spring.kafka.bootstrap-servers}
